// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// utils.cpp
double logspace_sub_cpp(double lx, double ly);
extern "C" SEXP _incubate_logspace_sub_cpp(SEXP lx, SEXP ly) {
  BEGIN_CPP11
    return cpp11::as_sexp(logspace_sub_cpp(cpp11::as_cpp<cpp11::decay_t<double>>(lx), cpp11::as_cpp<cpp11::decay_t<double>>(ly)));
  END_CPP11
}
// utils.cpp
double logspace_sub2_cpp(doubles lxy);
extern "C" SEXP _incubate_logspace_sub2_cpp(SEXP lxy) {
  BEGIN_CPP11
    return cpp11::as_sexp(logspace_sub2_cpp(cpp11::as_cpp<cpp11::decay_t<doubles>>(lxy)));
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_incubate_logspace_sub2_cpp", (DL_FUNC) &_incubate_logspace_sub2_cpp, 1},
    {"_incubate_logspace_sub_cpp",  (DL_FUNC) &_incubate_logspace_sub_cpp,  2},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_incubate(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
