# Generated by cpp11: do not edit by hand

logspace_sub_cpp <- function(lx, ly) {
  .Call(`_incubate_logspace_sub_cpp`, lx, ly)
}

logspace_sub2_cpp <- function(lxy) {
  .Call(`_incubate_logspace_sub2_cpp`, lxy)
}
